
export const actionIds = {
    AUTHORS_GET_DATA: "AUTHORS_GET_DATA",
    AUTHORS_GET_DATA_REQUEST: "AUTHORS_GET_DATA_REQUEST",
    AUTHORS_GET_DATA_SUCCESS: "AUTHORS_GET_DATA_SUCCESS",
    AUTHORS_GET_DATA_FAILURE: "AUTHORS_GET_DATA_FAILURE",

    AUTHOR_DETAILS_GET_DATA: "AUTHOR_DETAILS_GET_DATA",
    AUTHOR_DETAILS_GET_DATA_REQUEST: "AUTHOR_DETAILS_GET_DATA_REQUEST",
    AUTHOR_DETAILS_GET_DATA_SUCCESS: "AUTHOR_DETAILS_GET_DATA_SUCCESS",
    AUTHOR_DETAILS_GET_DATA_FAILURE: "AUTHOR_DETAILS_GET_DATA_FAILURE",

    BOOKS_GET_DATA: "BOOKS_GET_DATA",
    BOOKS_GET_DATA_REQUEST: "BOOKS_GET_DATA_REQUEST",
    BOOKS_GET_DATA_SUCCESS: "BOOKS_GET_DATA_SUCCESS",
    BOOKS_GET_DATA_FAILURE: "BOOKS_GET_DATA_FAILURE",

    BOOK_DETAILS_GET_DATA: "BOOK_DETAILS_GET_DATA",
    BOOK_DETAILS_GET_DATA_REQUEST: "BOOK_DETAILS_GET_DATA_REQUEST",
    BOOK_DETAILS_GET_DATA_SUCCESS: "BOOK_DETAILS_GET_DATA_SUCCESS",
    BOOK_DETAILS_GET_DATA_FAILURE: "BOOK_DETAILS_GET_DATA_FAILURE",

    GENRES_GET_DATA: "GENRES_GET_DATA",
    GENRES_GET_DATA_REQUEST: "GENRES_GET_DATA_REQUEST",
    GENRES_GET_DATA_SUCCESS: "GENRES_GET_DATA_SUCCESS",
    GENRES_GET_DATA_FAILURE: "GENRES_GET_DATA_FAILURE",

    GENRE_DETAILS_GET_DATA: "GENRE_DETAILS_GET_DATA",
    GENRE_DETAILS_GET_DATA_REQUEST: "GENRE_DETAILS_GET_DATA_REQUEST",
    GENRE_DETAILS_GET_DATA_SUCCESS: "GENRE_DETAILS_GET_DATA_SUCCESS",
    GENRE_DETAILS_GET_DATA_FAILURE: "GENRE_DETAILS_GET_DATA_FAILURE",

    BOOK_INSTANCES_GET_DATA: "BOOK_INSTANCES_GET_DATA",
    BOOK_INSTANCES_GET_DATA_REQUEST: "BOOK_INSTANCES_GET_DATA_REQUEST",
    BOOK_INSTANCES_GET_DATA_SUCCESS: "BOOK_INSTANCES_GET_DATA_SUCCESS",
    BOOK_INSTANCES_GET_DATA_FAILURE: "BOOK_INSTANCES_GET_DATA_FAILURE",

    BOOK_INSTANCE_DETAILS_GET_DATA: "BOOK_INSTANCE_DETAILS_GET_DATA",
    BOOK_INSTANCE_DETAILS_GET_DATA_REQUEST: "BOOK_INSTANCE_DETAILS_GET_DATA_REQUEST",
    BOOK_INSTANCE_DETAILS_GET_DATA_SUCCESS: "BOOK_INSTANCE_DETAILS_GET_DATA_SUCCESS",
    BOOK_INSTANCE_DETAILS_GET_DATA_FAILURE: "BOOK_INSTANCE_DETAILS_GET_DATA_FAILURE",
}